### PR TITLE
Crystal 0.8.0 support

### PR DESCRIPTION
**Pull request by veelenga**
- shards as dependency manager
 - `TimeFormat` -> `Time::Format`

### CODE REVIEW

**Comment by veelenga** [comment]
Not sure why tests are failing. Wrong db setup.

**Comment by drujensen** [comment]
:+1: Thanks!

**Comment by drujensen** [comment]
@veelenga I changed this to development_dependencies so it won't install all three db drivers.  You need to pick which driver(s) you want in your project.

I still haven't resolved why sqlite is failing in travis.

**Comment by veelenga** [comment]
Good catch with development_dependencies :+1:

**Pull request merged**
